/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Alien Resurrection)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x00015FA0u
#define func_00015FA0 BootEntry  /* alias */
